const test=require('node:test'),assert=require('node:assert/strict');
const {BombBustersLogicService}=require('../dist/game-room/bomb-busters-logic.service');
const audio=require('../dist/game-room/bomb-busters/campaign-audio');
const {BOMB_AUDIO_STEPS}=require('../dist/game-room/bomb-busters/audio-definitions');
const engine=new BombBustersLogicService(),all=s=>s.players.flatMap(p=>p.racks.flatMap(r=>r.wires));
const api={shuffle:xs=>[...xs],finish(s,outcome,reason){Object.assign(s,{phase:'finished',outcome,endReason:reason});},endTurn(s){s.currentPlayerId=s.players[(s.players.findIndex(p=>p.id===s.currentPlayerId)+1)%s.players.length].id;s.turnNumber++;s.campaign.turn=null;},applyCut(){throw Error('unexpected helper cut');},updateEquipment(){}};
function fixture(id,layout=[[1,2,3],[1,2,3],[4,5,6]]){const s=engine.initializeGame(['p0','p1','p2'],['A','B','C'],id,'p0');s.players.forEach((p,i)=>{p.racks=[{id:`r${i}`,wires:layout[i].map((value,j)=>({id:`w${i}-${j}`,value,sortValue:typeof value==='number'?value:5.1,cut:false,hint:null}))}];p.initialHintPlaced=true;});Object.assign(s,{phase:'playing',currentPlayerId:'p0',maxMistakes:10,mistakes:0,log:[],equipment:[]});Object.assign(s.campaign,{pending:null,turn:null,setupTasks:[],oxygen:{p0:6,p1:6,p2:6}});audio.configureBombAudio(s,api);return s;}
function cmd(s,operation,extra={},actor='p0',now=1000){return audio.applyBombAudioCommand(s,s.players.find(p=>p.id===actor),{type:'mission',operation,...extra},api,now);}
function enter(s,index){s.audio.status='running';s.audio.pending=null;s.audio.stepIndex=index-1;s.audio.deadlineAt=1000;audio.tickBombAudio(s,api,1000);}
function ack(s,now=2000){cmd(s,'audio_ack',{},s.captainId,now);}
function turn(s,value,ids,kind='dual',success=true){s.campaign.turn={actorId:s.currentPlayerId,kind,value,uncutIds:ids,mistakesBefore:s.mistakes,effectsApplied:true};if(success)all(s).filter(w=>ids.includes(w.id)).forEach(w=>w.cut=true);}

test('all five audio missions protect internal deck/reserve and only captain can start',()=>{for(const id of [19,30,42,54,66]){const s=fixture(id);s.audio.numberDeck=[123456];s.audio.reserveRed.push({id:'private-reserve',value:'red',sortValue:9.5});for(const viewer of ['p0','p1',undefined,'outsider']){const v=audio.bombAudioView(s,viewer),json=JSON.stringify(v);assert.equal(v.status,'ready');assert.ok(!json.includes('123456'));assert.ok(!json.includes('private-reserve'));assert.equal(v.controls.length,viewer==='p0'?1:0);}assert.throws(()=>cmd(s,'audio_start',{},'p1'));}});
test('setup clues remain possible but normal play waits for audio start',()=>{const s=fixture(19);assert.throws(()=>audio.validateBombAudioAction(s,s.players[0],{type:'solo',value:1}));s.phase='setup';assert.doesNotThrow(()=>audio.validateBombAudioAction(s,s.players[0],{type:'hint',wireId:'w0-0'}));});
test('19 enforces 600 active seconds while explanation time is paused',()=>{const s=fixture(19);cmd(s,'audio_start');let now=1000,total=0;for(let i=0;i<5;i++){const n=BOMB_AUDIO_STEPS[19][i].durationSeconds;now+=n*1000;total+=n;assert.equal(audio.tickBombAudio(s,api,now-1),false);assert.equal(audio.tickBombAudio(s,api,now),true);if(i<4){assert.equal(s.audio.status,'paused');assert.equal(s.audio.deadlineAt,null);assert.equal(audio.tickBombAudio(s,api,now+100000),false);now+=100000;ack(s,now);}}assert.equal(total,600);assert.equal(s.outcome,'lost');});
test('30 first penalty counts previously cut wires and equipment penalty discards smallest card',()=>{const s=fixture(30);enter(s,1);assert.deepEqual(s.audio.targets,[1]);enter(s,2);assert.equal(s.mistakes,1);const t=fixture(30);t.audio.targets=[1];all(t).filter(w=>w.value===1).forEach(w=>w.cut=true);enter(t,2);assert.equal(t.mistakes,0);const u=fixture(30);u.audio.targets=[12];u.equipment=[{id:6,name:'six',used:false},{id:2,name:'two',used:false}];enter(u,4);assert.deepEqual(u.equipment.map(e=>e.id),[6]);});
test('30 muting restricts violation reports to the affected player',()=>{const s=fixture(30);s.audio.targets=[12];enter(s,6);assert.deepEqual(s.audio.mutedIds,['p0']);ack(s);cmd(s,'audio_speech_violation');assert.equal(s.mistakes,1);assert.throws(()=>cmd(s,'audio_speech_violation',{},'p1'));});
test('30 three-target stage restricts numbers and wins without requiring other wires',()=>{const s=fixture(30);s.audio.numberDeck=[1,2,3,4];s.audio.targets=[12];enter(s,8);ack(s);assert.throws(()=>audio.validateBombAudioCut(s,s.players[0],9));assert.doesNotThrow(()=>audio.validateBombAudioCut(s,s.players[0],1));const t=fixture(30,[[1,1,1,1,9],[2,2,2,2,8],[3,3,3,3,7]]);t.audio.targets=[1,2,3];all(t).filter(w=>[1,2,3].includes(w.value)).forEach(w=>w.cut=true);enter(t,9);assert.equal(t.outcome,'won');assert.ok(all(t).some(w=>!w.cut));});
test('30 yellow rescue succeeds only with every remaining yellow and otherwise immediately loses',()=>{const s=fixture(30,[['yellow',1],['yellow',2],[3,4]]);s.audio.targets=[10,11,12];enter(s,9);cmd(s,'audio_yellow_rescue',{wireIds:['w0-0','w1-0']});assert.equal(s.audio.pending.kind,'ack');assert.equal(all(s).filter(w=>w.value==='yellow'&&!w.cut).length,0);ack(s);assert.equal(s.audio.deadlineAt,122000);const t=fixture(30,[['yellow',1],['yellow',2],[3,4]]);t.audio.targets=[10,11,12];enter(t,9);cmd(t,'audio_yellow_rescue',{wireIds:['w0-0','w1-1']});assert.equal(t.outcome,'lost');});
test('54 reserves eleven unique red wires and only receiver sees incoming rack-choice value',()=>{const s=fixture(54);assert.equal(s.audio.reserveRed.length,11);assert.equal(new Set(s.audio.reserveRed.map(w=>w.sortValue)).size,11);assert.equal(all(s).filter(w=>w.value==='red').length,0);s.players[0].racks.push({id:'r0b',wires:[]});enter(s,1);assert.equal(s.audio.pending.kind,'red_rack');assert.ok(audio.bombAudioView(s,'p0').instructions.some(x=>x.includes('1.5')));assert.ok(!audio.bombAudioView(s,'p1').instructions.some(x=>x.includes('1.5')));cmd(s,'audio_red_rack',{rackId:'r0b'});assert.equal(s.audio.reserveRed.length,10);assert.equal(s.players[0].racks[1].wires[0].value,'red');});
test('54 oxygen transfer validates ownership/amount and repeat turn is consumed once',()=>{const s=fixture(54);enter(s,5);assert.throws(()=>cmd(s,'audio_transfer',{targetPlayerId:'p1',direction:'give',value:7}));cmd(s,'audio_transfer',{targetPlayerId:'p1',direction:'take',value:3});assert.equal(s.campaign.oxygen.p0,9);assert.equal(s.campaign.oxygen.p1,3);enter(s,2);s.currentPlayerId='p1';audio.afterBombAudioTurn(s,'p0',api);assert.equal(s.currentPlayerId,'p0');assert.equal(s.audio.repeatPlayerId,null);assert.equal(BOMB_AUDIO_STEPS[54].reduce((n,x)=>n+x.durationSeconds,0),600);});
test('nonterminal cue defers detector result, but final deadline never defers',()=>{const s=fixture(19);cmd(s,'audio_start');s.pendingDetector={actorId:'p0'};assert.equal(audio.tickBombAudio(s,api,s.audio.deadlineAt),false);s.audio.stepIndex=4;assert.equal(audio.tickBombAudio(s,api,s.audio.deadlineAt),true);assert.equal(s.outcome,'lost');});
test('66 deadline runs during a pending move and completed goals wait for checkpoint',()=>{const s=fixture(66);cmd(s,'audio_start');s.audio.pending={kind:'move',actorId:'p0',value:1,remainingMoves:1};audio.tickBombAudio(s,api,s.audio.deadlineAt);assert.equal(s.outcome,'lost');const t=fixture(66);cmd(t,'audio_start');t.audio.bunker.doorOpen=true;assert.throws(()=>audio.validateBombAudioAction(t,t.players[0],{type:'solo',value:1}));assert.equal(audio.tickBombAudio(t,api,t.audio.deadlineAt-1),false);audio.tickBombAudio(t,api,t.audio.deadlineAt);assert.equal(t.audio.bunker.stage,'neutralize_guard');assert.equal(t.audio.status,'paused');});
test('66 successful and failed cuts both move without pausing time',()=>{for(const success of [true,false]){const s=fixture(66);cmd(s,'audio_start');s.audio.bunker.constraints={north:'E',east:'A',south:'B',west:'D',action:'C'};turn(s,1,['w0-0','w1-0'],'dual',success);const deadline=s.audio.deadlineAt;assert.equal(audio.afterBombAudioCut(s,api),true);assert.equal(s.audio.status,'running');assert.equal(s.audio.deadlineAt,deadline);cmd(s,'audio_move',{direction:'south'});assert.deepEqual(s.audio.bunker.position,[0,1]);assert.equal(s.audio.pending,null);}});
test('66 ACTION failure stays in place and yellow waits for laser',()=>{const s=fixture(66);cmd(s,'audio_start');s.audio.bunker.position=[1,2];s.audio.bunker.constraints.action='B';turn(s,1,['w0-0','w1-0'],'dual',false);assert.equal(audio.afterBombAudioCut(s,api),false);assert.equal(s.audio.bunker.doorOpen,false);assert.deepEqual(s.audio.bunker.position,[1,2]);assert.throws(()=>audio.validateBombAudioCut(s,s.players[0],'yellow'));});
test('66 laser can use two teammates yellow wires and red causes instant loss',()=>{for(const red of [false,true]){const s=fixture(66,[[1,2],['yellow',3],[red?'red':'yellow',4]]);cmd(s,'audio_start');Object.assign(s.audio.bunker,{floor:'basement',position:[3,2],stage:'disable_laser'});cmd(s,'audio_laser',{wireIds:['w1-0','w2-0']});assert.equal(red?s.outcome:s.audio.bunker.laserDisabled,red?'lost':true);}});
test('66 rearrangement is captain-controlled with ten-second window and premature victory is blocked',()=>{const s=fixture(66);s.audio.bunker.stage='disable_laser';s.audio.bunker.laserDisabled=true;enter(s,4);ack(s);const before=s.audio.bunker.constraints.north;cmd(s,'audio_bunker_swap',{direction:'east',cardId:before});assert.equal(s.audio.bunker.constraints.east,before);assert.throws(()=>cmd(s,'audio_bunker_swap',{direction:'east',cardId:before},'p1'));audio.tickBombAudio(s,api,s.audio.deadlineAt);assert.equal(s.audio.bunker.stage,'handcuff_doctor');assert.equal(audio.bombAudioAllowsVictory(s),false);s.audio.bunker.stage='finish_defusal';assert.equal(audio.bombAudioAllowsVictory(s),true);});

test('real engine completes setup for every audio mission with two to five players',()=>{
 for(const mission of [19,30,42,54,66])for(let count=2;count<=5;count++){
  const ids=Array.from({length:count},(_,i)=>`p${i}`),s=engine.initializeGame(ids,ids,mission,'p0');
  for(let i=0;s.phase==='setup'&&i<30;i++){
   const spectator=engine.getPlayerView(s,'p0'),actorId=spectator.campaign?.pendingActorId&&spectator.campaign.pendingActorId!=='any'?spectator.campaign.pendingActorId:s.currentPlayerId;
   const view=engine.getPlayerView(s,actorId),control=view.campaign?.controls?.[0];
   if(control){const action={type:'mission',operation:control.id};if(control.cards?.length)action.cardId=control.cards[0].id;engine.applyAction(s,actorId,action);}
   else {assert.equal(s.campaign.pending,null,JSON.stringify({mission,count,actorId,pending:s.campaign.pending,public:spectator.campaign}));const own=s.players.find(p=>p.id===actorId),wire=own.racks.flatMap(r=>r.wires).find(w=>typeof w.value==='number');engine.applyAction(s,actorId,{type:'hint',wireId:wire.id});}
  }
  assert.equal(s.phase,'playing',`setup ${mission}/${count}`);assert.equal(s.audio.status,'ready');
  engine.applyAction(s,'p0',{type:'mission',operation:'audio_start'});assert.equal(s.audio.status,'running');
  for(const viewer of [...ids,undefined]){const view=engine.getPlayerView(s,viewer);assert.equal(view.audio,undefined);assert.equal(view.campaign.audio.status,'running');assert.equal(view.campaign.audio.reserveRed,undefined);}
 }
});
test('real engine holds a cut until bunker movement resolves, then advances exactly once',()=>{
 const s=fixture(66);s.audio.bunker.constraints={north:'E',east:'A',south:'B',west:'D',action:'C'};
 engine.applyAction(s,'p0',{type:'mission',operation:'audio_start'});const deadline=s.audio.deadlineAt;
 engine.applyAction(s,'p0',{type:'dual',ownWireId:'w0-0',targetPlayerId:'p1',targetWireIds:['w1-0']});
 assert.equal(s.audio.pending.kind,'move');assert.equal(s.currentPlayerId,'p0');assert.equal(s.turnNumber,1);
 engine.applyAction(s,'p0',{type:'mission',operation:'audio_move',direction:'south'});
 assert.deepEqual(s.audio.bunker.position,[0,1]);assert.equal(s.audio.pending,null);assert.equal(s.currentPlayerId,'p1');assert.equal(s.turnNumber,2);assert.equal(s.audio.deadlineAt,deadline);
});
test('real engine rejects unauthorised audio state mutations atomically and hides 42 all faces during magician selection',()=>{
 const s=fixture(19),copy=structuredClone(s);assert.throws(()=>engine.applyAction(s,'p1',{type:'mission',operation:'audio_start'}));assert.deepEqual(s,copy);
 const t=fixture(42);t.audio.status='paused';t.audio.pending={kind:'magician',actorId:'p0'};t.audio.hideCutCounts=true;all(t).forEach(w=>{w.hint=w.value;w.clue={kind:'value',value:w.value};w.cut=true;});
 for(const viewer of ['p1',undefined,'outsider']){const view=engine.getPlayerView(t,viewer);assert.deepEqual(view.cutCounts,{});for(const p of view.players)for(const r of p.racks)for(const w of r.wires){assert.equal(w.value,null);assert.equal(w.sortValue,null);assert.equal(w.hint,null);assert.equal(w.clue,undefined);}}
});

test('66 two wrong laser guesses let the team choose exactly one hint while clock continues',()=>{const s=fixture(66,[[1,2],[3,4],[5,6]]);cmd(s,'audio_start');Object.assign(s.audio.bunker,{floor:'basement',position:[3,2],stage:'disable_laser'});const deadline=s.audio.deadlineAt;cmd(s,'audio_laser',{wireIds:['w1-0','w2-0']});assert.equal(s.mistakes,1);assert.equal(s.audio.pending.kind,'laser_hint');assert.equal(s.audio.deadlineAt,deadline);assert.throws(()=>cmd(s,'audio_laser_hint',{cardId:'w1-1'}));cmd(s,'audio_laser_hint',{cardId:'w2-0'});assert.equal(all(s).find(w=>w.id==='w2-0').hint,5);assert.equal(all(s).find(w=>w.id==='w1-0').hint,null);assert.equal(s.currentPlayerId,'p1');});
test('66 stabilizer prevents a red explosion in the laser attempt without publishing red information',()=>{const s=fixture(66,[[1,2],['yellow',3],['red',4]]);cmd(s,'audio_start');s.stabilizerActive=true;Object.assign(s.audio.bunker,{floor:'basement',position:[3,2],stage:'disable_laser'});cmd(s,'audio_laser',{wireIds:['w1-0','w2-0']});assert.equal(s.outcome,null);assert.equal(s.mistakes,0);assert.equal(s.audio.bunker.laserDisabled,false);assert.equal(all(s).find(w=>w.id==='w2-0').hint,null);});
test('54 finished players cannot receive oxygen and a lone remaining player skips transfer selection',()=>{const s=fixture(54);s.players[1].racks[0].wires.forEach(w=>w.cut=true);enter(s,5);assert.ok(!audio.bombAudioView(s,'p0').controls[0].playerIds.includes('p1'));assert.throws(()=>cmd(s,'audio_transfer',{targetPlayerId:'p1',value:0,direction:'give'}));s.players[2].racks[0].wires.forEach(w=>w.cut=true);enter(s,5);assert.equal(s.audio.pending.kind,'ack');});
